language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - vendor/bin/phpunit --coverage-clover '/tmp/clover.xml'

after_script:
  - ./cc-test-reporter format-coverage /tmp/clover.xml --input-type clover --output /tmp/clover.json
  - ./cc-test-reporter upload-coverage -i /tmp/clover.json -r $CC_TEST_REPORTER_ID
